## MySQL
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/UhHxcstHOJ
    username: UhHxcstHOJ
    password: jgxsfW3zm2
  # drop n create table, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  ssl:
    key-store: src\main\resources\keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
    key-password: password
  port: 8443
